# This Action autogenerates PDFs and standalone HTML
# out of your Overleaf projects (or any LaTeX-live project).
#
# PDF  generator: pdflatex
#
# Both tools come from LaTeX Live and are executed on
# the latest version of Ubuntu.
#
#    Given:
#       A repository with a LaTeX project with sobCV.tex in the root folder
#
#    On every push:
#       This GitHub Action builds the project with LaTeX Live.
#       A   PDF version of sobCV.tex is uploaded to a Release called "Current."
#           (Make sure that release exists first)

name: Build and Deploy Staffans CV PDF
permissions: write-all

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allow manual triggering

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up LaTeX environment
      - name: Install LaTeX
        run: |
          sudo apt update
          #sudo apt install -y texlive-latex-recommended, texlive-latex-extra, texlive-fonts-extra
          sudo apt install -y texlive-full

      # Step 3: Compile LaTeX to PDF
      - name: Compile LaTeX to PDF
        run: |
          mkdir -p output
          pdflatex -interaction=nonstopmode -output-directory=output sobCV.tex

      # Step 4: Upload PDF as an artifact
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: LaTeX-PDF
          path: "output/Staffan Bjornson CV.pdf"

  create-release:
    needs: build-pdf
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository (needed to determine version/tag)
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up GitHub CLI (if you prefer `gh`)
      - name: Install GitHub CLI
        run: sudo apt install gh

      - name: Fetch all tags
        run: git fetch --tags

      - name: Generate unique tag

        run: |
          BUILD_NUMBER=${{ github.run_number }}
          TAG="v1.0.0-${BUILD_NUMBER}"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Check if tag exists
        run: |
          if git rev-parse $TAG >/dev/null 2>&1
          then
            echo "Tag $TAG already exists. Skipping release creation."
            exit 1
          fi

      # Step 3: Create a GitHub Release and Upload the PDF
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: "LaTeX PDF Release ${{ env.TAG }}"
          body: "This release contains the latest compiled LaTeX PDF."
          draft: false
          prerelease: false

      # Step 4: Upload the PDF to the Release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: "output/Staffan Bjornson CV"
          asset_name: "Staffan Bjornson CV.pdf"
          asset_content_type: application/pdf
