# This Action autogenerates PDFs and standalone HTML 
# out of your Overleaf projects (or any LaTeX-live project).
# 
# PDF  generator: pdflatex
# 
# Both tools come from LaTeX Live and are executed on 
# the latest version of Ubuntu.
# 
#    Given:
#       A repository with a LaTeX project with sobCV.tex in the root folder
#   
#    On every push:
#       This GitHub Action builds the project with LaTeX Live. 
#       A   PDF version of sobCV.tex is uploaded to a Release called "Current." 
#           (Make sure that release exists first)



name: Build and Deploy Staffans CV PDF
permissions: write-all

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Latex PDF 
        run: |
          sudo apt update
          sudo apt install texlive-base teslive-pictures make
          mkdir ./public
          cp *.tex *.cls public/
          cp -r icons/ public/
          cp Makefile
          cd public/
          #pdflatex sobCV.tex
          make
          pwd
          ls -AlF
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artefact
      uses: actions/checkout@v3
      with:
        name: Build Latex PDF
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
