name: Build and Deploy Staffans CV PDF
permissions: write-all

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allow manual triggering

jobs:
  build-latex:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up LaTeX environment
      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-xetex

      # Build the LaTeX file
      - name: Build PDF from LaTeX
        run: |
          mkdir -p build
          pdflatex -output-directory=build sobCV.tex
          mv build/sobCV.pdf "Staffan Bjornson CV.pdf"

      # Prepare ZIP file
      - name: Prepare Release ZIP
        env:
          TAG: ${{ github.ref_name }}
        run: |
          BUILD_NUMBER=${{ github.run_number }}
          ZIP_NAME="Staffan Bjornson CV-${TAG}-${BUILD_NUMBER}.zip"
          zip -j "${ZIP_NAME}" "Staffan Bjornson CV.pdf"
          echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_ENV

      # Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          body: "This release includes the updated CV PDF."
          draft: false
          prerelease: false

      # Upload the ZIP file to the release
      - name: Upload ZIP to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ZIP_NAME }}
          asset_name: ${{ env.ZIP_NAME }}
          asset_content_type: application/zip
